import type { Bi } from "./types";
const b = (es: string, en: string): Bi => ({ es, en });
export const studies = [
  {
    id: "edwards2023",
    year: 2023,
    author: "Edwards, Acheson-Field, Rennane & Zaber",
    title:
      "Mapping scientists’ career trajectories in the survey of doctorate recipients using three statistical methods",
    url: "https://www.nature.com/articles/s41598-023-34809-1",
    tags: ["Métodos", "EE. UU."],
    scope: b(
      "9.076 doctorados STEM de EE. UU.; cohortes 2000–2008, observadas durante 7–9 años.",
      "9,076 US STEM doctorates; 2000–2008 cohorts followed for 7–9 years.",
    ),
    finding: b(
      "Las carreras fuera de academia son habituales. La diversidad de recorridos hace poco útil hablar de una única carrera «tradicional».",
      "Nonacademic careers are common. The diversity of paths makes a single “traditional” career a poor description.",
    ),
    use: b(
      "Mirar transiciones y años transcurridos, además del primer empleo. La muestra no cubre todas las disciplinas ni cohortes recientes.",
      "Look at transitions and elapsed time, beyond the first job. The sample does not cover every discipline or recent cohorts.",
    ),
  },
  {
    id: "boman2025",
    year: 2025,
    author: "Boman, Sánchez-Barrioluengo & van der Weijden",
    title:
      "Determinants of the career pathways of doctorate holders: Evidence from eight European universities",
    url: "https://link.springer.com/article/10.1007/s10734-025-01418-y",
    tags: ["Europa", "Investigación"],
    scope: b(
      "Encuesta a 1.678 personas doctoradas de ocho universidades europeas.",
      "Survey of 1,678 doctorate holders from eight European universities.",
    ),
    finding: b(
      "Trabajar en investigación fuera de la universidad también puede ser una elección deseada. La colaboración externa y la financiación privada se asocian con carreras de I+D empresarial.",
      "Research outside universities can be a desired choice. External collaboration and private funding are associated with business R&D careers.",
    ),
    use: b(
      "Separar sector y función: salir de academia no implica dejar de investigar. Las asociaciones no demuestran causalidad.",
      "Separate sector from function: leaving academia does not mean leaving research. Associations do not establish causality.",
    ),
  },
  {
    id: "postdoc2022",
    year: 2022,
    author: "PLOS ONE",
    title: "Postdoctoral employment and future non-academic career prospects",
    url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0278091",
    tags: ["Europa", "Postdoc"],
    scope: b(
      "Tesis doctorales y registros laborales alemanes enlazados en cinco grandes campos.",
      "German dissertations linked to employment records across five broad fields.",
    ),
    finding: b(
      "El estudio no encuentra una prima salarial general por haber realizado un postdoc antes de pasar al empleo no académico.",
      "The study does not find a general wage premium from doing a postdoc before moving into nonacademic employment.",
    ),
    use: b(
      "Valorar el postdoc por la experiencia y el destino buscados; no asumir que eleva los ingresos posteriores en cualquier sector.",
      "Evaluate a postdoc against the experience and destination you want; do not assume it raises later earnings in every sector.",
    ),
  },
  {
    id: "hancock2023",
    year: 2023,
    author: "Sally Hancock",
    title:
      "Knowledge or science-based economy? The employment of UK PhD graduates in research roles beyond academia",
    url: "https://doi.org/10.1080/03075079.2023.2249023",
    tags: ["Europa", "Investigación"],
    scope: b(
      "4.731 doctorados domiciliados en Reino Unido, en dos cohortes de la encuesta longitudinal DLHE.",
      "4,731 UK-domiciled doctorate holders in two longitudinal DLHE cohorts.",
    ),
    finding: b(
      "Las oportunidades de investigación fuera de academia difieren según la disciplina; las ciencias tienen un patrón distinto al de humanidades y ciencias sociales.",
      "Research opportunities beyond academia vary by discipline; sciences show a different pattern from humanities and social sciences.",
    ),
    use: b(
      "Buscar la función concreta del puesto, además del nombre de la empresa. Las cohortes son históricas.",
      "Check the actual function of a role, not just the employer. These are historical cohorts.",
    ),
  },
  {
    id: "lawson2024",
    year: 2024,
    author: "Lawson & Lopes-Bento",
    title:
      "Miss or match? The impact of PhD training on job market satisfaction",
    url: "https://doi.org/10.1016/j.respol.2023.104945",
    tags: ["Europa", "Bienestar"],
    scope: b(
      "Encuesta a solicitantes de financiación doctoral, con distintos resultados de formación y empleo.",
      "Survey of doctoral funding applicants with different training and employment outcomes.",
    ),
    finding: b(
      "El empleo no académico no se asocia automáticamente con menor satisfacción. Importan el encaje entre formación, tareas y expectativas.",
      "Nonacademic employment does not automatically mean lower satisfaction. Fit between training, tasks and expectations matters.",
    ),
    use: b(
      "Incluir satisfacción y uso de habilidades junto al salario. El diseño y la selección de la muestra limitan la generalización.",
      "Consider satisfaction and use of skills alongside salary. Design and sample selection limit generalisation.",
    ),
  },
  {
    id: "trace2024",
    year: 2024,
    author: "TRaCE Transborder",
    title: "TRaCE Transborder: Quantitative Report",
    url: "https://www.mcgill.ca/trace/files/trace/trace_transborder_quantitative_report_june_10_2024_final.pdf",
    tags: ["Humanidades", "Internacional"],
    scope: b(
      "Doctorados en humanidades de 12 universidades en cinco continentes; cohortes 2013–2022.",
      "Humanities doctorates from 12 universities across five continents; 2013–2022 cohorts.",
    ),
    finding: b(
      "Un seguimiento internacional de destinos permite observar funciones y contextos laborales que las bases bibliométricas no capturan.",
      "International destination tracking reveals work functions and contexts that bibliometric databases miss.",
    ),
    use: b(
      "Referencia especialmente útil para humanidades. La búsqueda pública puede no localizar a quienes tienen menos presencia en internet.",
      "Especially useful for humanities. Public searches may miss graduates with a smaller online presence.",
    ),
  },
  {
    id: "aarhus2025",
    year: 2025,
    author: "Aarhus University",
    title: "PhD Employment Survey 2025",
    url: "https://phd.au.dk/fileadmin/phd/Quality_in_PhD_education/Employment_Studies_for_PhD_graduates/PhD_report_2025.pdf",
    tags: ["Europa", "Todas las áreas"],
    scope: b(
      "Graduados de Aarhus de 2020–2021 y 2024–2025; situación en octubre de 2025.",
      "Aarhus graduates from 2020–2021 and 2024–2025; status in October 2025.",
    ),
    finding: b(
      "El seguimiento diferencia facultades, tiempo desde el título, empleadores y trabajo en Dinamarca o en el extranjero.",
      "The follow-up separates faculties, time since graduation, employers and work in Denmark or abroad.",
    ),
    use: b(
      "Modelo de encuesta institucional con detalle útil. Una universidad no representa el mercado de todo un país.",
      "A useful model for detailed institutional surveys. One university does not represent an entire national labour market.",
    ),
  },
  {
    id: "docenhance2021",
    year: 2021,
    author: "Boman, Beeson, Sánchez-Barrioluengo & Ruşitoru",
    title:
      "What comes after a PhD? Findings from the DocEnhance survey of doctorate holders on their employment situation, skills match, and the value of the doctorate",
    url: "https://doi.org/10.5281/zenodo.7188085",
    tags: ["Europa", "Habilidades"],
    scope: b(
      "Seguimiento de doctorados de nueve universidades europeas.",
      "Follow-up of doctorate holders from nine European universities.",
    ),
    finding: b(
      "Conecta sector de empleo, tareas y ajuste de habilidades. La formación investigadora convive con necesidades de comunicación y gestión.",
      "Connects employment sector, tasks and skills fit. Research training sits alongside needs in communication and management.",
    ),
    use: b(
      "Traducir experiencias del doctorado a tareas profesionales. No convertir un resultado institucional en tasa europea.",
      "Translate doctoral experience into professional tasks. Do not turn institutional findings into a European rate.",
    ),
  },
  {
    id: "brown2023",
    year: 2023,
    author: "Brown et al.",
    title:
      "From goal to outcome: Analyzing the progression of biomedical sciences PhD careers in a longitudinal study using an expanded taxonomy",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10626162/",
    tags: ["Biomedicina", "Métodos"],
    scope: b(
      "1.452 graduados en ciencias biomédicas de Vanderbilt, 1997–2021.",
      "1,452 Vanderbilt biomedical sciences graduates, 1997–2021.",
    ),
    finding: b(
      "Una taxonomía más detallada permite distinguir aspiraciones, sectores y funciones a lo largo de la carrera.",
      "A more detailed taxonomy distinguishes aspirations, sectors and functions across a career.",
    ),
    use: b(
      "Registrar varios momentos y no reducir cada persona a una sola etiqueta. Evidencia de una institución y un área.",
      "Record multiple time points rather than reduce a person to a single label. Evidence is from one institution and field.",
    ),
  },
  {
    id: "mathur2018",
    year: 2018,
    author: "Mathur et al.",
    title:
      "Visualization of gender, race, citizenship and academic performance in association with career outcomes of 15-year biomedical doctoral alumni at a public research university",
    url: "https://doi.org/10.1371/journal.pone.0197473",
    tags: ["Biomedicina", "EE. UU."],
    scope: b(
      "Seguimiento institucional de doctorados biomédicos de 1999–2014.",
      "Institutional tracking of biomedical doctorates from 1999–2014.",
    ),
    finding: b(
      "El empleo puede describirse con más precisión al combinar el tipo de organización y la actividad profesional.",
      "Employment is described more precisely by combining organisation type with professional activity.",
    ),
    use: b(
      "Complementar los grandes sectores con funciones. El diseño institucional no es un censo de biomedicina.",
      "Complement broad sectors with functions. Institutional tracking is not a census of biomedical graduates.",
    ),
  },
  {
    id: "aha",
    year: 2021,
    author: "American Historical Association",
    title: "Where Historians Work",
    url: "https://www.historians.org/community-careers/where-historians-work/",
    tags: ["Humanidades", "EE. UU."],
    scope: b(
      "12.310 doctorados en Historia; grupos observados en 2017 y 2021.",
      "12,310 history doctorates; groups observed in 2017 and 2021.",
    ),
    finding: b(
      "Hace visibles destinos en enseñanza, administración, empresa y organizaciones culturales, además de universidades.",
      "Makes teaching, administration, business and cultural organisations visible alongside universities.",
    ),
    use: b(
      "Un directorio de destinos documenta posibilidades. No estima bien el desempleo de personas no localizadas.",
      "A destination directory documents possibilities. It does not reliably measure unemployment among unlocated graduates.",
    ),
  },
  {
    id: "apda",
    year: 2024,
    author: "Academic Philosophy Data & Analysis",
    title: "APDA: placement data, coverage and methods",
    url: "https://www.philosophydata.org/about",
    tags: ["Humanidades", "Métodos"],
    scope: b(
      "Programas anglófonos de Filosofía; cobertura especialmente amplia de 2011–2024.",
      "Anglophone philosophy programmes; particularly extensive 2011–2024 coverage.",
    ),
    finding: b(
      "Publica información anonimizada por programa, cohorte e individuo, con revisión y corrección de registros.",
      "Publishes anonymised information by programme, cohort and individual, with record review and correction.",
    ),
    use: b(
      "Ejemplo de profundidad en una disciplina. La cobertura declarada por el proyecto no implica cobertura mundial.",
      "An example of depth in one discipline. Project-reported coverage does not imply worldwide coverage.",
    ),
  },
  {
    id: "taxonomy",
    year: 2018,
    author: "Mathur et al.",
    title:
      "Evolution of a functional taxonomy of career pathways for biomedical trainees",
    url: "https://doi.org/10.1017/cts.2018.22",
    tags: ["Métodos", "Todas las áreas"],
    scope: b(
      "Marco de clasificación de destinos profesionales del doctorado.",
      "Framework for classifying doctoral career outcomes.",
    ),
    finding: b(
      "Distinguir sector, tipo de carrera y función ayuda a comparar resultados sin confundir empleador con trabajo realizado.",
      "Distinguishing sector, career type and function helps comparison without confusing employer and work performed.",
    ),
    use: b(
      "Usar dimensiones separadas. Un contrato temporal, un sector y una función no son categorías equivalentes.",
      "Use separate dimensions. A temporary contract, a sector and a function are not equivalent categories.",
    ),
  },
  {
    id: "oecd2010",
    year: 2010,
    author: "OECD",
    title: "Careers of Doctorate Holders: Employment and Mobility Patterns",
    url: "https://doi.org/10.1787/5kmh8phxvvf5-en",
    tags: ["Internacional", "Métodos"],
    scope: b(
      "Proyecto internacional Careers of Doctorate Holders.",
      "International Careers of Doctorate Holders project.",
    ),
    finding: b(
      "La comparación internacional necesita definiciones comunes de población, empleo y movilidad.",
      "International comparison needs common population, employment and mobility definitions.",
    ),
    use: b(
      "Base metodológica histórica. No usar sus cifras como retrato del mercado laboral actual.",
      "A historical methodological foundation. Its figures are not a portrait of today’s labour market.",
    ),
  },
];

export const sectors = [
  b("Todas las funciones", "All functions"),
  b("Investigación", "Research"),
  b("Empresa y tecnología", "Business & technology"),
  b("Sociedad y políticas", "Society & policy"),
  b("Educación y cultura", "Education & culture"),
];
export const careers = [
  [
    "research",
    "Investigación académica",
    "Academic research",
    1,
    "Diseñar proyectos, publicar y desarrollar una agenda de investigación. El postdoc suele ser una fase distinta del empleo académico estable.",
    "Design projects, publish and develop a research agenda. A postdoc is often a different stage from permanent academic employment.",
    "Diseño de estudios · escritura · métodos",
    "Study design · writing · methods",
    "edwards2023",
  ],
  [
    "industry",
    "I+D en empresa",
    "Business R&D",
    1,
    "Aplicar conocimiento especializado a productos, procesos y experimentos. Puede haber investigación sin docencia ni publicación abierta.",
    "Apply specialist knowledge to products, processes and experiments. Research may take place without teaching or open publication.",
    "Experimentación · validación · colaboración",
    "Experimentation · validation · collaboration",
    "boman2025",
  ],
  [
    "publicresearch",
    "Institutos y laboratorios públicos",
    "Public research institutes",
    1,
    "Investigar problemas de interés público en institutos, laboratorios y organismos especializados.",
    "Research public-interest problems in institutes, laboratories and specialist agencies.",
    "Métodos · documentación · proyectos",
    "Methods · documentation · projects",
    "hancock2023",
  ],
  [
    "data",
    "Análisis de datos y estadística",
    "Data analysis & statistics",
    2,
    "Convertir datos en decisiones: medir, modelizar, evaluar incertidumbre y comunicar resultados.",
    "Turn data into decisions: measure, model, evaluate uncertainty and communicate results.",
    "Estadística · programación · comunicación",
    "Statistics · programming · communication",
    "docenhance2021",
  ],
  [
    "software",
    "Software y aprendizaje automático",
    "Software & machine learning",
    2,
    "Construir sistemas reproducibles y evaluar modelos. La experiencia de investigación necesita acompañarse de prácticas de ingeniería.",
    "Build reproducible systems and evaluate models. Research experience needs to be complemented by engineering practice.",
    "Programación · evaluación · reproducibilidad",
    "Programming · evaluation · reproducibility",
    "hancock2023",
  ],
  [
    "consulting",
    "Consultoría y análisis estratégico",
    "Consulting & strategic analysis",
    2,
    "Estructurar problemas abiertos, contrastar evidencia y presentar decisiones con plazos concretos.",
    "Structure open-ended problems, assess evidence and present decisions within specific deadlines.",
    "Síntesis · análisis · presentaciones",
    "Synthesis · analysis · presentation",
    "docenhance2021",
  ],
  [
    "finance",
    "Economía, finanzas y bancos centrales",
    "Economics, finance & central banks",
    3,
    "Investigar mercados, evaluar riesgos y analizar políticas. El directorio de Economía ofrece ejemplos de empleadores concretos.",
    "Research markets, assess risk and analyse policy. The economics directory provides specific employer examples.",
    "Econometría · modelos · informes",
    "Econometrics · models · reports",
    "boman2025",
  ],
  [
    "policy",
    "Políticas públicas y evaluación",
    "Public policy & evaluation",
    3,
    "Evaluar programas, sintetizar investigación y asesorar sobre decisiones públicas.",
    "Evaluate programmes, synthesise research and inform public decisions.",
    "Evaluación · síntesis · escritura",
    "Evaluation · synthesis · writing",
    "hancock2023",
  ],
  [
    "nonprofit",
    "Organizaciones sociales y ONG",
    "Nonprofits & civil society",
    3,
    "Diseñar y evaluar intervenciones, producir evidencia y coordinar proyectos orientados a una misión.",
    "Design and evaluate interventions, produce evidence and coordinate mission-led projects.",
    "Evaluación · trabajo de campo · proyectos",
    "Evaluation · fieldwork · projects",
    "boman2025",
  ],
  [
    "ux",
    "Investigación de usuarios",
    "User research",
    2,
    "Investigar necesidades y comportamientos mediante entrevistas, observación y experimentos.",
    "Investigate needs and behaviour through interviews, observation and experiments.",
    "Métodos cualitativos · experimentos · síntesis",
    "Qualitative methods · experiments · synthesis",
    "docenhance2021",
  ],
  [
    "teaching",
    "Docencia y diseño del aprendizaje",
    "Teaching & learning design",
    4,
    "Enseñar, desarrollar materiales y evaluar aprendizajes dentro o fuera de la universidad.",
    "Teach, develop materials and evaluate learning within or beyond universities.",
    "Docencia · diseño · evaluación",
    "Teaching · design · evaluation",
    "aha",
  ],
  [
    "culture",
    "Museos, archivos y patrimonio",
    "Museums, archives & heritage",
    4,
    "Investigar colecciones, documentar patrimonio y hacer accesible el conocimiento a distintos públicos.",
    "Research collections, document heritage and make knowledge accessible to different audiences.",
    "Documentación · investigación · mediación",
    "Documentation · research · interpretation",
    "trace2024",
  ],
  [
    "publishing",
    "Edición y comunicación científica",
    "Publishing & science communication",
    4,
    "Revisar y transformar conocimiento complejo en publicaciones, contenidos y recursos accesibles.",
    "Review and translate complex knowledge into accessible publications, content and resources.",
    "Escritura · edición · comunicación",
    "Writing · editing · communication",
    "trace2024",
  ],
  [
    "management",
    "Gestión de investigación",
    "Research management",
    1,
    "Coordinar convocatorias, proyectos, financiación y relaciones entre equipos e instituciones.",
    "Coordinate grants, projects, funding and relationships between teams and institutions.",
    "Planificación · presupuestos · coordinación",
    "Planning · budgeting · coordination",
    "brown2023",
  ],
  [
    "transfer",
    "Transferencia e innovación",
    "Knowledge transfer & innovation",
    2,
    "Conectar conocimiento, organizaciones y usos: colaboración, valorización y desarrollo de proyectos.",
    "Connect knowledge, organisations and applications through collaboration and project development.",
    "Negociación · proyectos · comunicación",
    "Negotiation · projects · communication",
    "boman2025",
  ],
  [
    "health",
    "Salud y desarrollo clínico",
    "Health & clinical development",
    1,
    "Investigar intervenciones, ensayos y resultados en salud. Los puestos asistenciales pueden exigir habilitación profesional específica.",
    "Research interventions, trials and health outcomes. Clinical practice roles may require specific professional licensing.",
    "Investigación · calidad · regulación",
    "Research · quality · regulation",
    "brown2023",
  ],
  [
    "entrepreneur",
    "Emprendimiento y trabajo independiente",
    "Entrepreneurship & independent work",
    2,
    "Desarrollar un servicio o producto propio, o prestar investigación y asesoría especializada por proyectos.",
    "Develop your own service or product, or provide specialist research and advice through projects.",
    "Autonomía · clientes · gestión",
    "Independence · clients · management",
    "docenhance2021",
  ],
  [
    "international",
    "Organismos internacionales",
    "International organisations",
    3,
    "Analizar problemas entre países, evaluar políticas y elaborar evidencia para programas internacionales.",
    "Analyse cross-country problems, evaluate policy and produce evidence for international programmes.",
    "Análisis · idiomas · colaboración",
    "Analysis · languages · collaboration",
    "oecd2010",
  ],
].map(([id, es, en, sector, des, de, skills, skillsEn, study]) => ({
  id: String(id),
  title: b(String(es), String(en)),
  sector: Number(sector),
  description: b(String(des), String(de)),
  skills: b(String(skills), String(skillsEn)),
  study: String(study),
}));

export const institutions: Record<string, string> = {
  berkeley: "UC Berkeley",
  bonn: "University of Bonn",
  bostonu: "Boston University",
  brown: "Brown University",
  cambridge: "University of Cambridge",
  chicago: "University of Chicago",
  columbia: "Columbia University",
  cornell: "Cornell University",
  duke: "Duke University",
  eui: "European University Institute",
  harvard: "Harvard University",
  lse: "London School of Economics",
  maryland: "University of Maryland",
  michigan: "University of Michigan",
  minnesota: "University of Minnesota",
  mit: "MIT",
  northwestern: "Northwestern University",
  nyu: "New York University",
  oxford: "University of Oxford",
  princeton: "Princeton University",
  stanford: "Stanford University",
  ucl: "University College London",
  ucla: "UCLA",
  ucsd: "UC San Diego",
  upenn: "University of Pennsylvania",
  upf: "Universitat Pompeu Fabra",
  warwick: "University of Warwick",
  yale: "Yale University",
  zurich: "University of Zurich",
};
export const placementTypes: Record<string, Bi> = {
  tenure_track: b("Puesto académico¹", "Academic position¹"),
  private: b("Privado²", "Private²"),
  postdoc: b("Postdoc", "Postdoc"),
  central_bank: b("Banco central", "Central bank"),
  international_org: b("Organismo internacional", "International organisation"),
  government: b("Gobierno", "Government"),
  think_tank: b("Think tank", "Think tank"),
};
