export type Lang = "es" | "en";
export type Bi = { es: string; en: string };
export type Row = {
  id: string;
  field: string;
  label: Bi;
  family: string;
  broad: boolean;
  year: string;
  horizon: string;
  total: number | null;
  denominator: number | null;
  values: (number | null)[];
  salary: number | null;
  salaryN?: number;
  salaryLow?: number;
  salaryHigh?: number;
  salarySectors?: (number | null)[];
  cohort?: string;
  committed?: number;
  abroad?: number;
  unknownLocation?: number;
  employment?: number | null;
  unemployment?: number | null;
  stable?: number | null;
  fulltime?: number | null;
  se?: (number | null)[];
  unmatched?: number;
};
export type Dataset = {
  id: string;
  name: Bi;
  kind: string;
  year: string;
  country: string;
  unit: string;
  currency: string;
  salaryPeriod: string;
  title: Bi;
  population: Bi;
  denominator: Bi;
  note: Bi;
  url: string;
  table?: string;
  salaryTable?: string;
  license: string;
  categories: Bi[];
  records: Row[];
};
export type Placement = {
  id: string;
  name: string;
  year: number;
  employer: string;
  institution: string;
  field: string;
  type: string;
  originalRegion: string;
};
export type Source = {
  id: string;
  fuente: string;
  ambito: string;
  nivel: string;
  aporte: string;
  acceso: string;
  vigencia: string;
  limite: string;
  reutilizacion: string;
  prioridad: string;
  verificacion: string;
  url: string;
};
export type DataTable = {
  id: string;
  title: string;
  source: string;
  rows: number;
  columns: number;
  url: string;
};
